language: ruby
rvm:
  - 2.1.2

branch:
  only:
    - master

cache: bundler
install: bundle install --jobs=3 --retry=3

script:
  - bundle exec rspec .

after_success:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST
  - test $TRAVIS_BRANCH == "master" && echo hello
